# -*- coding: utf-8 -*-
"""CNN Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt8NKSqbOkwz8iTbt1K-sy0HwNdbl5Tb
"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/archive.zip"
extract_path = "/content/data"

import zipfile

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete!")

import os
train_dir = "/content/data/data/train"
val_dir = "/content/data/data/val"
test_dir = "/content/data/data/test"
print("Train directory exists:", os.path.exists(train_dir))
print("Validation directory exists:", os.path.exists(val_dir))
print("Test directory exists:", os.path.exists(test_dir))

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Image size & batch size
img_size = 224  # Adjust as needed
batch_size = 32  # You can increase this based on your system

# Data Augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1.0/255,  # Normalize pixel values between 0-1
    rotation_range=20,  # Randomly rotate images
    width_shift_range=0.2,  # Randomly shift width
    height_shift_range=0.2,  # Randomly shift height
    shear_range=0.2,  # Apply shear transformation
    zoom_range=0.2,  # Apply zoom
    horizontal_flip=True,  # Flip images horizontally
    fill_mode='nearest'
)

# For validation & test (Only rescaling)
val_test_datagen = ImageDataGenerator(rescale=1.0/255)

# Load training images
train_generator = train_datagen.flow_from_directory(
    directory=train_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'  # Since you have two classes (awake/sleepy)
)

# Load validation images
val_generator = val_test_datagen.flow_from_directory(
    directory=val_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary'
)

# Load test images
test_generator = val_test_datagen.flow_from_directory(
    directory=test_dir,
    target_size=(img_size, img_size),
    batch_size=batch_size,
    class_mode='binary',
    shuffle=False  # No need to shuffle test data
)

# Print class indices
print("Class indices:", train_generator.class_indices)

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
import matplotlib.pyplot as plt

# ✅ Load Pretrained MobileNetV2
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

# ✅ Build Model
x = base_model.output
x = GlobalAveragePooling2D()(x)  # Reduce overfitting
x = Dropout(0.4)(x)  # Higher dropout for regularization
x = Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01))(x)  # L2 Regularization
x = Dropout(0.3)(x)  # More dropout to prevent overfitting
output_layer = Dense(1, activation='sigmoid')(x)  # Binary classification

model = Model(inputs=base_model.input, outputs=output_layer)

LEARNING_RATE = 0.0001
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# ✅ Callbacks to Prevent Overfitting
callbacks = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1, min_lr=1e-6),
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1)
]

history = model.fit(train_generator,
                    validation_data=val_generator,
                    epochs=10,  # Train longer to improve generalization
                    callbacks=callbacks)

model.save("drowsiness_model.keras")
model_path_keras = "/content/drive/My Drive/drowsiness_model.keras"
model.save(model_path_keras)