# -*- coding: utf-8 -*-
"""XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxE179yyB4KtPN56rbXWhZ3s2YheLHuj
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
# Load dataset from your Drive
df = pd.read_csv("/content/drive/MyDrive/MEFAR_MID.csv")

import joblib

# Load the trained model from file
model_path = '/content/drive/MyDrive/rf_physio_model.joblib'
model = joblib.load(model_path)

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
import joblib

# Drop any missing values
df.dropna(inplace=True)

# Separate features and target
X = df.drop(columns=["class"])
y = df["class"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train XGBoost
xgb_model = xgb.XGBClassifier(
    n_estimators=100,        # Number of boosting rounds
    learning_rate=0.1,       # Learning rate
    max_depth=6,             # Maximum depth of the trees
    subsample=0.8,           # Subsample ratio of the training data
    colsample_bytree=0.8,    # Subsample ratio of features
    random_state=42,
    n_jobs=-1                # Use all available cores for parallel processing
)
xgb_model.fit(X_train, y_train)

# Evaluate the model
y_pred = xgb_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Save the model
joblib.dump(xgb_model, "xgb_physio_model.joblib")

import joblib
joblib.dump(xgb_model, "/content/drive/MyDrive/xgb_physio_model.joblib")

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

ConfusionMatrixDisplay.from_estimator(xgb_model, X_test, y_test, cmap="Blues")
plt.title("Test Set Confusion Matrix")
plt.show()

import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.metrics import accuracy_score

# Lists to store accuracy values
train_accuracies = []
test_accuracies = []
n_estimators_list = range(10, 201, 20)  # Varying number of trees

for n in n_estimators_list:
    model = xgb.XGBClassifier(
        n_estimators=n,        # Varying the number of trees
        learning_rate=0.1,     # Set a fixed learning rate
        max_depth=6,           # Set a fixed maximum depth
        random_state=42,
        n_jobs=-1              # Use all available cores for parallel processing
    )
    model.fit(X_train, y_train)

    # Accuracy on train and test sets
    train_acc = accuracy_score(y_train, model.predict(X_train))
    test_acc = accuracy_score(y_test, model.predict(X_test))

    train_accuracies.append(train_acc)
    test_accuracies.append(test_acc)

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(n_estimators_list, train_accuracies, label="Train Accuracy", marker='o')
plt.plot(n_estimators_list, test_accuracies, label="Test Accuracy", marker='s')
plt.xlabel("Number of Trees (n_estimators)")
plt.ylabel("Accuracy")
plt.title("Train vs Test Accuracy - XGBoost")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Drop missing values (if any) reloading
df.dropna(inplace=True)

# Separate features and target
X = df.drop(columns=['class'])  # or your actual target column name
y = df['class']

import seaborn as sns
import matplotlib.pyplot as plt

# Combine X and y back into a DataFrame
df = X.copy()
df['class'] = y

# Correlation of features with target
correlation = df.corr(numeric_only=True)['class'].sort_values(ascending=False)
print("Feature correlation with class:\n", correlation)

# Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

